# Backpropogation Neural Network example

This is a Jupyter notebook to test the backpropogation example presented by Matt Mazur (https://mattmazur.com/2015/03/17/a-step-by-step-backpropagation-example/). It is used to test computational methods for implementing the process he described in a procedural way so that they can be expanded to be used on a larger neural network.

In [1]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

INPUT_NEURONS = 2
HIDDEN_NEURONS = 2
OUTPUT_NEURONS = 2

LEARNING_RATE = 0.5

training_iterations = 0

In [2]:
hl_weights = np.array([[0.15, 0.20],[0.25, 0.30]]) # rows, columns
ol_weights = np.array([[0.40, 0.45],[0.50, 0.55]])
hidden_bias = 0.35
output_bias = 0.60

In [3]:
hl_weights

array([[0.15, 0.2 ],
       [0.25, 0.3 ]])

In [4]:
ol_weights

array([[0.4 , 0.45],
       [0.5 , 0.55]])

In [5]:
# FORWARD PASS
input_vals = np.array([0.05, 0.10])

In [6]:
# calculating hidden layer outputs
hidden_nets = np.array([np.dot(w, input_vals)+hidden_bias for w in hl_weights])
hidden_outputs = sigmoid(hidden_nets)

In [7]:
hidden_nets

array([0.3775, 0.3925])

In [8]:
hidden_outputs

array([0.59326999, 0.59688438])

In [9]:
# calculating output layer outputs
output_nets = np.array([np.dot(w, hidden_outputs)+output_bias for w in ol_weights])
output_outputs = sigmoid(output_nets)

In [10]:
output_nets

array([1.10590597, 1.2249214 ])

In [11]:
output_outputs

array([0.75136507, 0.77292847])

In [12]:
# calculating error
error = np.sum(0.5*(np.array([0.01, 0.99]) - output_outputs)**2)
error

0.2983711087600027

In [13]:
# BACKWARD PASS

# calculating the changes on the output layer weights
d_error_d_outs = -(np.array([0.01, 0.99]) - output_outputs)
d_outs_d_nets = output_outputs*(1-output_outputs)
#d_error_d_nets = np.multiply(d_error_d_outs, d_outs_d_nets)
d_error_d_nets = d_error_d_outs * d_outs_d_nets
d_nets_d_weights = np.array([hidden_outputs]*OUTPUT_NEURONS)

In [14]:
d_error_d_outs

array([ 0.74136507, -0.21707153])

In [15]:
d_outs_d_nets

array([0.1868156 , 0.17551005])

In [16]:
d_nets_d_weights

array([[0.59326999, 0.59688438],
       [0.59326999, 0.59688438]])

In [17]:
"""
d_error_d_weights = d_nets_d_weights
for i in range(0, OUTPUT_NEURONS):
    for j in range(0, HIDDEN_NEURONS):
        d_error_d_weights[i, j] = d_nets_d_weights[i, j] * d_error_d_nets[i]
        
d_error_d_weights
"""

'\nd_error_d_weights = d_nets_d_weights\nfor i in range(0, OUTPUT_NEURONS):\n    for j in range(0, HIDDEN_NEURONS):\n        d_error_d_weights[i, j] = d_nets_d_weights[i, j] * d_error_d_nets[i]\n        \nd_error_d_weights\n'

In [18]:
# a better version of the above calculation (multiplying d_error_d_nets into columns of d_nets_d_weights)
d_error_d_weights = (d_nets_d_weights.T * d_error_d_nets).T
d_error_d_weights

array([[ 0.08216704,  0.08266763],
       [-0.02260254, -0.02274024]])

In [19]:
new_ol_weights = np.subtract(ol_weights, LEARNING_RATE*d_error_d_weights)
new_ol_weights

array([[0.35891648, 0.40866619],
       [0.51130127, 0.56137012]])

In [20]:
# calculating the changes on the hidden layer weights

d_errors_d_hiddenouts = np.array([np.dot(d_error_d_nets, ol_weights[:,i]) for i in range(0, HIDDEN_NEURONS)])
d_errors_d_hiddenouts

array([0.03635031, 0.04137032])

In [21]:
d_outs_d_nets = hidden_outputs*(1-hidden_outputs)
d_outs_d_nets

array([0.24130071, 0.24061342])

In [22]:
d_error_d_nets = d_errors_d_hiddenouts*d_outs_d_nets
#d_error_d_nets = np.multiply(d_errors_d_hiddenouts, d_outs_d_nets)
d_error_d_nets

array([0.00877135, 0.00995425])

In [23]:
d_nets_d_weights = np.array([input_vals]*HIDDEN_NEURONS)
d_nets_d_weights

array([[0.05, 0.1 ],
       [0.05, 0.1 ]])

In [24]:
"""
d_error_d_weights = d_nets_d_weights
for i in range(0, HIDDEN_NEURONS):
    for j in range(0, INPUT_NEURONS):
        d_error_d_weights[i, j] = d_nets_d_weights[i, j] * d_error_d_nets[i]
        
d_error_d_weights
"""

'\nd_error_d_weights = d_nets_d_weights\nfor i in range(0, HIDDEN_NEURONS):\n    for j in range(0, INPUT_NEURONS):\n        d_error_d_weights[i, j] = d_nets_d_weights[i, j] * d_error_d_nets[i]\n        \nd_error_d_weights\n'

In [25]:
# a better version of the above calculation (multiplying d_error_d_nets into columns of d_nets_d_weights)
d_error_d_weights = (d_nets_d_weights.T * d_error_d_nets).T
d_error_d_weights

array([[0.00043857, 0.00087714],
       [0.00049771, 0.00099543]])

In [26]:
new_hl_weights = np.subtract(hl_weights, LEARNING_RATE*d_error_d_weights)
new_hl_weights

array([[0.14978072, 0.19956143],
       [0.24975114, 0.29950229]])